# Generated by Django 5.2.7 on 2025-12-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='certificados.certificado'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido_por_emisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='respondido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20),
        ),
        migrations.CreateModel(
            name='ArchivoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mensajes/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='mensajes.mensaje')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
