# Generated by Django 5.2.7 on 2025-12-15 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas_masivas/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Honorarios', 'Honorarios'), ('Servicios', 'Servicios'), ('Rentas', 'Rentas')], default='Honorarios', max_length=20)),
                ('cliente', models.CharField(max_length=100)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('periodo', models.CharField(default='2025', max_length=20)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('usuario_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/adjuntos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='certificados.certificado')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
