# Generated by Django 5.2.7 on 2025-12-11 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificado',
            name='monto_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='certificado',
            name='monto_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='certificado',
            name='periodo',
            field=models.CharField(default='2025', max_length=20),
        ),
        migrations.AddField(
            model_name='certificado',
            name='rut_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C')], default='A', max_length=1),
        ),
    ]
