# Generated by Django 5.2.7 on 2025-12-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('certificados', '0002_certificado_cliente_certificado_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='certificados.certificado'),
        ),
    ]
